# Generated by Django 6.0.2 on 2026-02-09 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], default='Movie', max_length=10)),
                ('title', models.CharField(max_length=225)),
                ('director', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('listed_in', models.TextField()),
                ('description', models.TextField()),
                ('content_soup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
